#!/bin/bash

# Change hostname on Debian-based Linux distros
# By Robbie Ferguson // baldnerd.com

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 2>&1
  exit 1
fi

hn=$(/bin/hostname)
echo Current Hostname: $hn
read -p "New Hostname: " hn_new

printf "Changing Hostname... "
/bin/sed -i -- 's/'"$hn"'/'"$hn_new"'/g' /etc/hosts
/bin/sed -i -- 's/'"$hn"'/'"$hn_new"'/g' /etc/hostname
hostnamectl set-hostname $hn_new
echo Done.
echo Change will take effect at next reboot.
