#!/bin/bash
# This FIO drive benchmark script written by Robbie Ferguson for Category5 TV Network.
# With lots of fantastic input and advice from the folks at Kingston Technology;
# Special thanks to David Leong, Mark Noland, Matthew Eaton and Cameron Crandall.

# Currently, this script is optimized for a 4-drive array. You will need to adjust
# values for numjobs and iodepth if you will be running this on a single drive,
# or anything other than a 4-drive array.

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 2>&1
  exit 1
fi

drive=$1
if [[ $drive == "" ]]; then
  echo "Usage: $0 /dev/sdX"
  echo "       where sdX is your actual drive (not partition)."
  echo "       Test is destructive. DO NOT run on production drives."
  echo "       Drive must not be mounted."
  exit 0
fi

# A simple but hopefully effective test to prevent accidental data corruption
mountcheck=$(mount | grep $drive)
if [[ $mountcheck != "" ]]; then
  echo "This drive is mounted and cannot be tested."
  echo "Did you know, this is a destructive test."
  echo "If you run the test on this drive, it will lose data."
  exit 1
fi

echo ""
echo "WARNING: Data on $drive will be destroyed."
echo ""
read -r -p "Are you sure? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
then

tmpdir=`mktemp -d -p /tmp/`

if [ $(dpkg-query -W -f='${Status}' fio 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
  printf "Installing fio... "
  apt update > /dev/null 2>&1
  apt-get install -y fio > /dev/null 2>&1
  if [ $(dpkg-query -W -f='${Status}' fio 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
    echo "Failed."
    exit 1
  else
    echo "Done."
  fi
fi

testEnd() {
  end=`date +%s`
  runtime=$((end-testStart))
  printf 'Test took: %dh %dm %ds to run.\n' $(($runtime/3600)) $(($runtime%3600/60)) $(($runtime%60))
  printf 'Test took: %dh %dm %ds to run.\n' $(($runtime/3600)) $(($runtime%3600/60)) $(($runtime%60)) >> /var/log/fio-test.log
}

printf "Generating tests for $drive... "

# rnd-read
echo "[rnd-read]
ioengine=libaio
direct=1
size=100%
bs=4k
rw=randread
numjobs=4
iodepth=32
runtime=600
time_based
norandommap
randrepeat=0
group_reporting
filename=$drive" > $tmpdir/rnd-read.ini

# rnd-write
echo "[rnd-write]
ioengine=libaio
direct=1
size=100%
bs=4k
rw=randwrite
numjobs=4
iodepth=32
runtime=600
time_based
norandommap
randrepeat=0
group_reporting
filename=$drive" > $tmpdir/rnd-write.ini

# seq-read
echo "[seq-read]
ioengine=libaio
direct=1
size=100%
bs=128k
rw=read
numjobs=1
iodepth=128
runtime=600
time_based
filename=$drive" > $tmpdir/seq-read.ini

# seq-write
echo "[seq-write]
ioengine=libaio
direct=1
size=100%
bs=128k
rw=write
numjobs=1
iodepth=128
runtime=600
time_based
filename=$drive" > $tmpdir/seq-write.ini

echo "[rnd-pc]
ioengine=libaio
direct=1
size=1G
bs=4k
rw=randwrite
numjobs=4
iodepth=32
loops=4
norandommap
randrepeat=0
group_reporting
filename=$drive" > $tmpdir/rnd-pc.ini

echo "[seq-pc]
ioengine=libaio
direct=1
size=100%
bs=128k
rw=write
numjobs=1
iodepth=128
loops=2
filename=$drive" > $tmpdir/seq-pc.ini

echo "Done."
echo ""
echo "Running tests..."

start=`date +%s`

datestamp=$(date)
echo "-------------------------------" >> /var/log/fio-test.log
echo "$datestamp - fio-test on $drive" >> /var/log/fio-test.log

# Run the tests in order recommended by Matt Eaton (FIO Specialist) via Mark Noland, Field Application Engineer at Kingston Digital Inc.

echo "Running seq-pc..."
echo "Running seq-pc..." >> /var/log/fio-test.log
testStart=`date +%s`
fio $tmpdir/seq-pc.ini >> /var/log/fio-test.log
testEnd

echo "Running seq-read..."
echo "Running seq-read..." >> /var/log/fio-test.log
testStart=`date +%s`
fio $tmpdir/seq-read.ini >> /var/log/fio-test.log
testEnd

echo "Running seq-write..."
echo "Running seq-write..." >> /var/log/fio-test.log
testStart=`date +%s`
fio $tmpdir/seq-write.ini >> /var/log/fio-test.log
testEnd

echo "Running rnd-pc..."
echo "Running rnd-pc..." >> /var/log/fio-test.log
testStart=`date +%s`
fio $tmpdir/rnd-pc.ini >> /var/log/fio-test.log
testEnd

echo "Running rnd-read..."
echo "Running rnd-read..." >> /var/log/fio-test.log
testStart=`date +%s`
fio $tmpdir/rnd-read.ini >> /var/log/fio-test.log
testEnd

echo "Running rnd-write..."
echo "Running rnd-write..." >> /var/log/fio-test.log
testStart=`date +%s`
fio $tmpdir/rnd-write.ini >> /var/log/fio-test.log
testEnd

echo "Finished."
echo "Finished." >> /var/log/fio-test.log
end=`date +%s`
runtime=$((end-start))
printf 'Total time: %dh %dm %ds to run.\n' $(($runtime/3600)) $(($runtime%3600/60)) $(($runtime%60))
printf 'Total time: %dh %dm %ds to run.\n' $(($runtime/3600)) $(($runtime%3600/60)) $(($runtime%60)) >> /var/log/fio-test.log

echo "Log has been saved to /var/log/fio-test.log"

rm -rf $tmpdir

else
  echo "Aborted."
  exit 0
fi
