#!/bin/bash
# Docker Community Edition for Linux Mint 19 / Ubuntu 18.04

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 2>&1
  exit 1
fi

apt-get update
apt-get -y install apt-transport-https ca-certificates curl software-properties-common gnupg
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
apt-key -y fingerprint 0EBFCD88
apt-key adv --keyserver hkps://keyserver.ubuntu.com --recv-keys 7EA0A9C3F273FCD8 # for Debian compatibility
#add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" > /etc/apt/sources.list.d/docker.list
apt-get update
apt-get -y install docker-ce
