#!/bin/bash
file=$1

duration=$(ffmpeg -i "$1" 2>&1 |grep -oP "[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{2}")
echo "Duration: $duration"

printf "Timestamp (00:00:00 or Enter if done): "

read timestamp

if [[ -n "$timestamp" ]]; then
  echo $timestamp
fi

ffmpeg -i "$file" -vn -acodec copy -ss $timestamp -to 00:01:32 OutputFile

