#!/bin/bash

command=$1
url=$2

if [[ $command == 'install' ]]; then
  # Install youtube-dl
  if [[ -e /usr/local/bin/youtube-dl ]]; then
    printf "Updating youtube-dl..."
  else
    printf "Installing youtube-dl..."
  fi
  sudo wget https://yt-dl.org/downloads/latest/youtube-dl -q -O /usr/local/bin/youtube-dl
  sudo chmod a+rx /usr/local/bin/youtube-dl
  version=$(/usr/local/bin/youtube-dl --version)
  echo "Done. Version $version installed."
  exit
fi

if [[ $url == '' ]]; then
  echo "Usage: $0 [task] [url]"
  echo ""
  echo "Available Tasks:"
  echo "  install - Install or update youtube-dl"
  echo "  mp4 - Download the MP4 video file"
  echo "  mp3 - Download the MP3 audio file"
  echo ""
fi

if [[ $command == 'mp4' ]]; then
  # Download video
  # Will grab the best version in MP4 format
  # Prevents ending up with webm files, etc.
  /usr/local/bin/youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4' $url
fi

if [[ $command == 'mp3' ]]; then
  # Download MP3 audio
  youtube-dl --extract-audio --audio-format mp3 $url
fi

